version: '3.8'

services:
  # Service RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"  # Port AMQP
      - "15672:15672"  # Port interface de gestion
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Producteur
  producer:
    build: .
    environment:
      - MODE=producer
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
    command: npm run dev:producer
    depends_on:
      rabbitmq:
        condition: service_healthy

  # Consommateur
  consumer:
    build: .
    environment:
      - MODE=consumer
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
    command: npm run dev:consumer
    depends_on:
      rabbitmq:
        condition: service_healthy

  # Interface Web
  web:
    build: .
    environment:
      - MODE=web
      - PORT=3000
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
    command: npm run dev:web
    depends_on:
      rabbitmq:
        condition: service_healthy

  # Workers pour chaque type d'opération
  worker-add:
    build: .
    environment:
      - MODE=worker
      - OPERATION=add
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
    command: npm run dev:worker
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker-sub:
    build: .
    environment:
      - MODE=worker
      - OPERATION=sub
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
    command: npm run dev:worker
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker-mul:
    build: .
    environment:
      - MODE=worker
      - OPERATION=mul
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
    command: npm run dev:worker
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker-div:
    build: .
    environment:
      - MODE=worker
      - OPERATION=div
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
    command: npm run dev:worker
    depends_on:
      rabbitmq:
        condition: service_healthy 